### ISSUE TITLE
Backend - AsyncLocal with TransactionId

### ISSUE THREAD

**Issue by Igasus** [Igasus/modular-house#12]
Create TransactionId in Middleware and store it in AsyncLocal

_Originally posted by @Vladislawv in https://github.com/Igasus/modular-house/pull/10#discussion_r1355333884_

**Comment by Vladislawv** [comment]
Every transaction should be able to track.

So, it's need to create TransactionMiddleware on the top of request pipeline which:

- Check if request has header "transactionId", if null => initialize header by generating new Guid;
- Set to CurrentTransaction.TransactionId value using AsyncLocal.
